apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-link-user-deployment
  namespace: mini-link-namespace
  labels:
    app: mini-link-user-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mini-link-user-label
  template:
    metadata:
      labels:
        app: mini-link-user-label
    spec:
      containers:
        - name: mini-link-user
          image: 镜像仓库IP:端口/minilink/mini-link-user:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: 300Mi
              cpu: 200m
            limits:
              memory: 500Mi
              cpu: 400m
          readinessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 10