apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-link-data-deployment
  namespace: mini-link-namespace
  labels:
    app: mini-link-data-label
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mini-link-data-label
  template:
    metadata:
      labels:
        app: mini-link-data-label
    spec:
      containers:
        - name: mini-link-gateway
          image: 镜像仓库IP:端口/minilink/mini-link-data:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          resources:
            requests:
              memory: 300Mi
              cpu: 200m
            limits:
              memory: 500Mi
              cpu: 400m
          readinessProbe:
            tcpSocket:
              port: 8003
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8003
            initialDelaySeconds: 60
            periodSeconds: 10