kind: Service
apiVersion: v1
metadata:
  name: mini-link-data-service
  namespace: mini-link-namespace
  labels:
    app: mini-link-data-label
spec:
  selector:
    app: mini-link-data-label
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
