kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: mini-link-namespace
  labels:
    app: mini-link-core-label
spec:
  selector:
    app: mini-link-core-label
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
