spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mini_link_user?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: Pxy123456
      timeout: 3000
      connectTimeout: 5000
      lettuce:
        pool:
          min-idle: 100
          max-idle: 100
          max-active: 100
          max-wait: 20000
  mail:
    host: smtp.qq.com
    port: 465
    username: 1262254123@qq.com
    password: ocebnufztunlbagc
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory