spring:
  datasource:
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://localhost:8123/default
    username: root
    password: test123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: test123456
      timeout: 3000
      connectTimeout: 5000
      lettuce:
        pool:
          min-idle: 100
          max-idle: 100
          max-active: 100
          max-wait: 20000