spring:
  cloud:
    gateway:
      routes:
        - id: mini-link-user
          uri: lb://mini-link-user
          predicates:
            - Path=/user/**

        - id: mini-link-core
          uri: lb://mini-link-core
          predicates:
            - Path=/url/**,/**