server:
  port: 9001
  servlet:
    context-path: /core
spring:
  profiles:
    active: dev
  application:
    name: mini-link-core
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
