mini-link:
  domain: localhost:8080/
  group-id: 1
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-dev.yaml
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: Pxy123456
      timeout: 3000
      connectTimeout: 5000
      lettuce:
        pool:
          min-idle: 100
          max-idle: 100
          max-active: 100
          max-wait: 20000