spring:
#  profiles:
#    active: dev
  application:
    name: mini-link-core
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-dev.yaml
server:
  port: 9001
  servlet:
    context-path: /api/core