#spring:
#  shardingsphere:
#    datasource:
#      names: ds0,ds1
#      ds0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/mini_link?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
#        username: root
#        password: Pxy161122
#      ds1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/mini_link?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
#        username: root
#        password: Pxy161122
#    rules:
#      sharding:
#        sharding-algorithms:
#          table-inline:
#            type: INLINE
#            props:
#              algorithm-expression: mini_link_url_$->{id % 3}
#        tables:
#          mini_link_url:
#            key-generate-strategy:
#              column: id
#              key-generator-name: SNOWFLAKE
#            actual-data-nodes: ds0.mini_link_url_$->{0..2}
#            table-strategy:
#              standard:
#                sharding-column: id
#                sharding-algorithm-name: table-inline
#    props:
#      sql:
#        show: true
