dataSources:
  ds0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/mini_link_core_0?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  ds1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/mini_link_core_1?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  ds2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/mini_link_core_2?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

rules:
  - !SHARDING
    tables:
      link_url_tob:
        actualDataNodes: ds${0..2}.link_url_tob_${0..1}
        databaseStrategy:
          standard:
            shardingColumn: account_id
            shardingAlgorithmName: link-url-tob-datasource-inline
        tableStrategy:
          standard:
            shardingColumn: account_id
            shardingAlgorithmName: link-url-tob-table-inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
    shardingAlgorithms:
      link-url-tob-datasource-inline:
        type: INLINE
        props:
          algorithm-expression: ds${account_id % 3}
      link-url-tob-table-inline:
        type: INLINE
        props:
          algorithm-expression: link_url_tob_${account_id % 2}
    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker:
            id: ${workerId}
props:
  sql-show: true
